### ISSUE TITLE
Individual expire not working

### ISSUE THREAD

**Issue by rfogel** [joshuaslate/type-cacheable#103]
Hello.

I'm trying to set a individual cache time to live but I'm not getting the expected result. I'm using NodeCache as cache platform. Here's my sample code:

```
const client = new NodeCache({ stdTTL: 120, checkperiod: 120 * 0.2 })
useNodeCacheAdapter(client)
```

```
@Cacheable({ ttlSeconds: 5 })
public async getAll(venueIds?: Array<string>) {
        return this.getAllByFilter(venueIds, sitesByVenue)
}
```

I tried setting hashKey and cacheKey, but no success. I also tried to create a custom CacheClient(wrap of a NodeCache) but not worked either.

I don't know if I doing something wrong or what.

**Comment by joshuaslate** [comment]
About to release something that I hope fixes this. Please let me know on v2.2.1 once it's released momentarily.

**Comment by rfogel** [comment]
OK, thanks for your quick reply. I'll check later.

**Comment by rfogel** [comment]
TTL seems to be working. Thanks Josh. 

FYI: Custom client on other hand seems not

**Comment by joshuaslate** [comment]
@rfogel, what seems to not be working with the custom client, so I can investigate?

**Comment by rfogel** [comment]
For example, i created a CacheClient implementation:

```
import NodeCache from 'node-cache'
import { CacheClient } from 'type-cacheable'

export class CacheClient2 implements CacheClient {
    public cache: NodeCache

    private defaultTTL: number

    constructor(stdTTL: number = 60 * 60) {
        this.defaultTTL = stdTTL
        this.cache = new NodeCache({ stdTTL, checkperiod: stdTTL * 0.2 })
    }

    async get<T>(cacheKey: string): Promise<T> {
        console.log('getting', cacheKey)
        return this.cache.get(cacheKey)
    }

    async set<T>(cacheKey: string, value: T, ttl?: number) {
        console.log('setting', cacheKey)
        this.cache.set(cacheKey, value, ttl)
    }

    async del(cacheKey: string | string[]): Promise<any> {
        this.cache.del(cacheKey)
    }

    async keys(pattern: string): Promise<string[]> {
        console.log(pattern)
        return this.cache.keys()
    }

    getClientTTL(): number {
        return this.defaultTTL
    }

    flush() {
        this.cache.flushAll()
    }
}

```

And I used it like this:

`export const cacheClient2 = new CacheClient2()`

```
@Cacheable({ client: cacheClient2 })
    public async getAll(venueIds?: Array<string>) {
        return this.getAllByFilter(venueIds, sitesByVenue)
 }
```
Am I doing it right? Is this supposed to work?

**Comment by joshuaslate** [comment]
I added a test here that seems to be passing. Note that I needed to make some small tweaks to your custom client implementation to get past some typing errors, but otherwise, it seems to be working for me: https://github.com/joshuaslate/type-cacheable/commit/57c7556160f44cbaff55ba59c93dff9cceeda124#diff-4f83e010711858fe0b863df874558aacR73

**Comment by rfogel** [comment]
So, is there any reason for console.log not been called? I'm new to javascript, so maybe I'm missing something.

**Comment by joshuaslate** [comment]
You should see `console.log` being called when there's no value cached for the given arguments (a cache miss) because the method will actually run in that case. If there's a cache hit, you wouldn't see the `console.log` because the method wouldn't actually run. It would just return the value from the last time it ran.

**Comment by rfogel** [comment]
I never saw console.log. What I thought it should work: If there ins't a cache, **set** method should be called and **get** method should always be called since the service needs to check if there's a value cached. On both methods, console.log are present.

**Comment by joshuaslate** [comment]
Your assumptions are right. Would you be able to add a failing test case that I can work on? I tried adding the code you provided, but for some reason, the tests I created are still passing 🤷‍♂

**Comment by joshuaslate** [comment]
Closing because this is a stale issue. Please provide more information if you can still repeat this.
