### ISSUE TITLE
[BUG] IoRedis adapter returns string values instead of Date

### ISSUE THREAD

**Issue by ZanchiStefano** [joshuaslate/type-cacheable#1066]
**Describe the bug**
Using IoRedis adapter, cache saves Date instance value as a string. Getting cached value returns string instead of Date instance.

**To Reproduce**
```
@Cacheable({ cacheKey: (args) => args[0], hashKey: 'getDateObject', ttlSeconds: 60 * 60 })
public getDate(anyKey: string): { myDate: Date } {
  return { myDate: new Date() }
}
  
public getCachedDate(): void {
  // setting cache first. Returns { myDate: Date }
  const response = this.getDate('some-key')

  // getting data from cache. Returns { myDate: string }
  const wrongResponse = this.getDate('some-key')
}
```

**Expected behavior**
Response should be consistent, doesn't matter if loaded from cache or not. Should return date if possible.

**Environment:**
 - OS: Windows 11 Pro
 - Version: 13.1.0
- Adapter IoRedis: 14.1.0

**Additional context**
It's the same problem as this issue https://github.com/joshuaslate/type-cacheable/issues/638, except that in this case it is on the IoRedis adapter.

**Comment by joshuaslate** [comment]
I just released updates, please try with the latest versions. Thanks for catching this.
