### ISSUE TITLE
[BUG] Wrong Peer Dependencies set

### ISSUE THREAD

**Issue by ZanchiStefano** [joshuaslate/type-cacheable#1068]
**Describe the bug**
After the last update of the core, from version 13 to 14, only the adapter's dev dependency were updated, the peer dependencies version were not updated.

**To Reproduce**
Install the core package and an adapter.

**Expected behavior**
No problems with the peer dependencies.

**Screenshots**

Installation made with pnpm:

![immagine](https://github.com/joshuaslate/type-cacheable/assets/138488456/0b88898f-aa8f-49e5-a0d9-d0a238638536)

**Environment:**

-  OS: Windows 11 Pro
-  Version: 14.0.0
-  Adapter: all the latest versions, ioredis 15, lru 17, node cache 14, redis 17

**Comment by joshuaslate** [comment]
Ah thank you, I'll fix this. I thought lerna automated this. Thanks!
