### ISSUE TITLE
Adapter inconsistencies

### ISSUE THREAD

**Issue by dvarnai** [joshuaslate/type-cacheable#113]
Redis and IoRedis adapters store values differently, IoRedisAdapter doesn't support hmset like RedisAdapter does. Furthermore, IoRedisAdapter doesn't do any transformation for numbers and strings.

As a better solution, I propose adding a transform function parameter to the cacheable decorator, that would by default transform objects, numbers, booleans. This would also make it possible to parse custom types automatically, making the rest of the application completely unaware whether the value was returned from cache or not.

Thoughts? If you reckon it's a good idea I'll submit a PR

**Comment by joshuaslate** [comment]
Thank you for the suggestion @dvarnai, that seems like a good idea if I'm understanding correctly.

So there would be an optional parameter to handle (de)serializing the return value of the decorated method, but we would provide a default implementation (as is the only option now)? This would give users the option to use non-native types.

I'd be happy to review a PR for this. Thank you for your contributions so far!

**Comment by dvarnai** [comment]
Yes that's exactly what I mean. Also, it might by a good idea to store strings escaped with surrounding quotations marks rather than store numbers booleans etc with a type identifier. This would eliminate any chance of falsely parsing actual strings as numbers or booleans etc and it would make it possible to store basic types as they would be stored in a json.

**Comment by dvarnai** [comment]
#116 

I added a draft PR with my implementation, please take a look whenever you get a chance. I imagine there are plenty of ways to make it nicer.
