### ISSUE TITLE
Implement sqlite-adapter/file-adapter

### ISSUE THREAD

**Issue by Oscaner** [joshuaslate/type-cacheable#1143]
**Is your feature request related to a problem? Please describe.**

I don't want to use any persistent cache client, such as Redis, or MongoDB. For offline projects, they're burdens.

But I need the persistent cache feature.

**Describe the solution you'd like**

We can create a sqlite-adapter or file-adapter to support this.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by joshuaslate** [comment]
Please try `@type-cacheable/cache-manager-adapter` like this:

```
import { sqliteStore } from '@resolid/cache-manager-sqlite';
import * as cacheManager from 'cache-manager';
import { join } from 'node:path';
import { useAdapter } from '@type-cacheable/cache-manager-adapter';

// An example using the @resolid/cache-manager-sqlite adapter
const store = sqliteStore({
  cacheTableName: 'cache',
  sqliteFile: join(process.cwd(), 'cache.sqlite3'),
});

const cacheManagerCache = cacheManager.createCache(store);

const clientAdapter = useAdapter(cacheManagerCache);
```

**Comment by Oscaner** [comment]
@joshuaslate Wow, it's a beautiful feature! Thanks!
