### ISSUE TITLE
Noop is not working when client is defined

### ISSUE THREAD

**Issue by asafbrill** [joshuaslate/type-cacheable#136]
Hi,
Setting the noop to true does not have any effect. 
Looking at Cacheable.ts, it looks like the noop check happens only if the client is not defined (which usually will not be the case). 

It would seem that it should be outside the if (!client) block...

**Comment by joshuaslate** [comment]
Hey there,

I'll try to take a look at this this weekend! I've been a bit busy lately, sorry for the delayed reply.

Best,

Josh
