### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by tomasstrejcek** [joshuaslate/type-cacheable#155]
Hi there, big thanks for this lib, it helps us tremendously!
But I need to ask you for a favor, could you always provide a changelog when releasing new version (with warnings for breaking changes ofc)?
It would greatly help everybody using your lib.
Thanks

**Comment by joshuaslate** [comment]
Hi Tomáš,

Yes, I'll try to add one going forward.

Best,

Josh

**Comment by joshuaslate** [comment]
I've generated a changelog here and will update it moving forward.

https://github.com/joshuaslate/type-cacheable/blob/master/CHANGELOG.md
