### ISSUE TITLE
Missing index.d.ts in latest release

### ISSUE THREAD

**Issue by taybin** [joshuaslate/type-cacheable#170]
After upgrading to the latest release, I see it's missing a types declaration file.  This should be included, right?  It was included in the older version I was using, 0.1.9.

**Comment by joshuaslate** [comment]
Hi @taybin, you're right. I'll look into this.

**Comment by joshuaslate** [comment]
Please check with v4.1.2. This seems to be working for me now.

**Comment by taybin** [comment]
That fixed it.  Thank you!
