### ISSUE TITLE
node-cache error

### ISSUE THREAD

**Issue by olehcambel** [joshuaslate/type-cacheable#180]
Since moving to latest version
```diff
- "type-cacheable": "^2.2.1",
+ "type-cacheable": "^4.1.2",
```

I'm getting error on ts build *. I use `ioredis` for caching. Should I install `node-cache` as devDependencies to fix it?
*
```bash
node_modules/type-cacheable/dist/adapters/NodeCacheAdapter.d.ts:1:28 - error TS2307: Cannot find module 'node-cache'.

1 import * as NodeCache from 'node-cache';
                             ~~~~~~~~~~~~

node_modules/type-cacheable/dist/util/useAdapter.d.ts:2:28 - error TS2307: Cannot find module 'node-cache'.

2 import * as NodeCache from 'node-cache';
     
```

**Comment by olehcambel** [comment]
Possible solution is to move `@types/node-cache` to dependencies

**Comment by olehcambel** [comment]
Also, reference to #110

**Comment by joshuaslate** [comment]
Hi @olehcambel,

I will try to look into the monorepo solution I mentioned before in order to fix this. I think that's the best way to approach this, so the adapters can remain completely separate from one another.

For the short-term, I guess you could try adding node-cache as a devDep.

**Comment by joshuaslate** [comment]
Hi Oleh, please try with the latest version, v5.0.1 and let me know if there are any issues. Note that the npm packages have been changed to:

```
@type-cacheable/core
@type-cacheable/redis-adapter
@type-cacheable/ioredis-adapter
@type-cachable/node-cache-adapter
```

You will need `@type-cacheable/core` and `@type-cacheable/ioredis-adapter`, then simply update your imports and things should work as in the latest v4 release otherwise.

**Comment by olehcambel** [comment]
Ok, thanks! I'll try a bit later and then close this issue

**Comment by olehcambel** [comment]
No, there is no issues. Everything is working as expected. I'm closing this issue
