### ISSUE TITLE
Configureable caching strategy

### ISSUE THREAD

**Issue by oschlegel** [joshuaslate/type-cacheable#189]
Do you thought about supporting different caching strategies? Currently your caching mechanism returns always the cached value if some exists, which is a kind of "Cache First" strategy. I thought of a "Cache as Fallback" strategy where the original method is always executed. In case the method returns a result within a certain timespan the result is returned and the Cache is updated. If the method doesn't Return a result in time the cached value is used and the Cache is updated when the method finally completes.

The caching strategy could bei passed as option to the cachable decorator like so:
```
@Cacheable({ strategy: new CacheAsFallbackStrategy(3000) })
```

The library could also expose a caching strategy interface, this way consumers could write their own caching strategies. Please Tell me what you think about this idea.

**Comment by joshuaslate** [comment]
Hi @oschlegel,

I hadn't considered that, but it does seem like a cool idea that I'd be open to exploring. I'll look into this when I have some free time.

Thank you!
