### ISSUE TITLE
Fallback to in-memory cache

### ISSUE THREAD

**Issue by oschlegel** [joshuaslate/type-cacheable#198]
In some cases it would be nice if a in-memory cache would be used by `Cachable` and `CacheClear` decorators if no other cache is defined. This would open the possibility to have a fallback for caching if a connection to the actual cache could not be established. This behavior should be optional, for example by a `fallbackToInMemoryCache` flag in the `CacheManager` options.

Why do you think of this idea?

**Comment by joshuaslate** [comment]
Hi @oschlegel, I don't think I want to include an in-memory cache implementation in core. An alternative idea would be to add an optional `fallbackClient`. Then the user could pass whichever implementation they'd prefer as a fallback. For an in-memory solution, the user could pass in an instance of `@type-cacheable/node-cache-adapter`. Would that accomplish what you're hoping for?

**Comment by oschlegel** [comment]
That sounds like a good solution

**Comment by joshuaslate** [comment]
Going to land in the next major version via #208.
