### ISSUE TITLE
Caching numeric values

### ISSUE THREAD

**Issue by OlivierKamers** [joshuaslate/type-cacheable#202]
Thank you for this great library, we have been able to make great use of it already!

So far we have been using it for methods that return objects. I wanted to cache a method that returns a number but at the moment it appears that caching a numeric value itself is not supported for the redis adapter. The cached value is returned as a string. This conversion is done on this line in the adapter:
https://github.com/joshuaslate/type-cacheable/blob/master/packages/redis-adapter/lib/index.ts#L232

For numeric/boolean values nested inside an object it looks like the conversion is done by adding an identifier: https://github.com/joshuaslate/type-cacheable/blob/master/packages/redis-adapter/lib/index.ts#L8-L11

Would it make sense to do the same for simple numeric and boolean values? Or drop the JSON.stringify for numbers/booleans?

**Comment by joshuaslate** [comment]
Hi @OlivierKamers, thank you for the kind words and for using the library!

The serialization and deserialization with redis are things I'd like to give another look to in general.

Maybe simply dropping JSON.stringify for numbers/booleans would be a good short-term solution though.

I'm not at my desk until later in the upcoming week, but can likely make the changes and release an update at that point.

**Comment by joshuaslate** [comment]
This should be fixed in v6. Please upgrade and test, but note that (de)serialization has changed entirely (got rid of the custom logic that seemed to not be necessary). This means previously cached values may not be read properly. I advise you to purge your cache when updating.

Please feel free to re-open this issue if this issue is not resolved.

**Comment by OlivierKamers** [comment]
Hi @joshuaslate!
Thank you for the update. We will try the new version asap and report back with the results 👍
