### ISSUE TITLE
Incorrect usage of "scan" while deleting pattern matched cache entries

### ISSUE THREAD

**Issue by evilworm** [joshuaslate/type-cacheable#204]
Currently we have single command being executed while deleting cached entries:

```
public async keys(pattern: string): Promise<string[]> {
  const result = await this.redisClient.scan('0', 'MATCH', `*${pattern}*`, 'COUNT', 1000);

  return result ? result[1] : [];
}
```

This is wrong. Redis SCAN command is cursor based and you need to check the response if the cursor position is "0". If it's not "0" then you need to continue executing the scan command in a loop.

I checked only the ioredis implementation, but it's probably true for other adapters as well. It should look something like this:

```
public async keys(pattern: string): Promise<string[]> {
  let keys:Array<string> = [];
  let cursor = 0;
  do {
    const result = await this.redisClient.scan(cursor, 'MATCH', `*${pattern}*`, 'COUNT', 1000);
    if(result) {
      cursor = Number(result[0]);
      keys = keys.concat(result[1]);
    } else {
      cursor = 0;
    }
  } while(cursor);

  return keys;
}
```

Also I would suggest dropping the hardcoded wildcards and let user decide where to put them. Most of the time you will have a constant prefix and wildcard only at the end. However this might be a breaking change to already implemented code...

**Comment by joshuaslate** [comment]
This should be fixed in v6. Please upgrade and test, but note that (de)serialization has changed entirely (got rid of the custom logic that seemed to not be necessary). This means previously cached values may not be read properly. I advise you to purge your cache when updating.

Please feel free to re-open this issue if this issue is not resolved.

**Comment by evilworm** [comment]
unfortunately this fix introduced endless loop because the cursor check is implemented incorrectly

you have:
`cursor = Number(result[0]) !== cursor ? Number(result[0]) : null;`

when result[0] is set to 0, the above logic will set cursor=0, however the while(...) checks for null value
so basically when cursor value is 0 you start the SCAN command from the beginning hence the endless loop

you should change this to:
`cursor = Number(result[0]) !== 0 ? Number(result[0]) : null;`

**Comment by joshuaslate** [comment]
@evilworm thank you for your contribution. I've released your update and added some extra tests to help ensure this is working as intended. Please let me know if the latest version of the adapter + core work for you.

**Comment by evilworm** [comment]
the fix seems to work correctly now
