### ISSUE TITLE
CacheUpdate is not working properly

### ISSUE THREAD

**Issue by luqezman** [joshuaslate/type-cacheable#214]
Hi again @joshuaslate :)

I was trying to use @CacheUpdate decorator from version 6.2.0 but for some behaviours I couldnt.

When I use @CacheUpdate on update operation, normally I have the my entity and possibility to set cacheKey by id, example:

```typescript
  @CacheUpdate({
    cacheKey: ([{ id }]: any[]) => id,
    cacheKeysToClear: 'todos',
  })
  async updateTodo(todo: Todo, dataToUpdate: TodoUpdateInput): Promise<Todo> {
    const todoToUpdate = Object.assign(todo, dataToUpdate);
    const updatedTodo = await this.todoRepository.save(todoToUpdate);

    return updatedTodo;
  }
```

Everything here works like a charm. But in my create operation I dont have id available immediatelly, example:

```typescript
  @CacheUpdate({
    cacheKey: (data: any[]) => {
       return 'invalid-id';
     },
     cacheKeysToClear: 'todos',
  })
  async createTodo(task: string): Promise<Todo> {
    const todoAsEntity = await this.todoRepository.create({ task });
    const todo = await this.todoRepository.save(todoAsEntity);

    return todo;
  }
```

When I try to create cacheKey data contains the task name instead of the result.

Any suggestions to fix it?

**Comment by joshuaslate** [comment]
Hi @luqezman,

I'll figure something more elegant out for this. Meanwhile, I'd recommend using the `@CacheClear` decorator above `createTodo()` and relying on your `@Cacheable`-decorated `getUser(id: string)` and `getUsers()` methods to populate the cache when called.

**Comment by luqezman** [comment]
@joshuaslate I did it, everything is working like a charm, just waiting a possibility to implement it on create. Check my code:

```typescript
@Injectable()
export class TodoService implements ITodoService {
  constructor(private readonly todoRepository: TodoRepository) {}

  @CacheClear({ cacheKey: 'todos' })
  async createTodo(task: string): Promise<Todo> {
    const todoAsEntity = await this.todoRepository.create({ task });
    const todo = await this.todoRepository.save(todoAsEntity);

    return todo;
  }

  @Cacheable({ cacheKey: 'todos' })
  async getAllTodos(): Promise<Todo[]> {
    const todos = await this.todoRepository.find();

    return todos;
  }

  @Cacheable({ cacheKey: ([id]: [string]) => id })
  async getTodoById(id: string): Promise<Todo | null> {
    const todo = await this.todoRepository.findOne(id);

    return todo;
  }

  @CacheClear({ cacheKey: ([id]: [string]) => [id, 'todos'] })
  async removeTodoById(id: string): Promise<boolean> {
    const { affected } = await this.todoRepository.delete(id);
    const hasBeenDeleted = affected > 0;

    return hasBeenDeleted;
  }

  @CacheUpdate({
    cacheKey: ([todo]: [Todo, TodoUpdateInput]) => todo.id,
    cacheKeysToClear: 'todos',
  })
  async updateTodo(
    todo: Todo,
    todoUpdateInput: TodoUpdateInput,
  ): Promise<Todo> {
    const todoToUpdate = Object.assign(todo, todoUpdateInput);
    const updatedTodo = await this.todoRepository.save(todoToUpdate);

    return updatedTodo;
  }
}
```

**Comment by luqezman** [comment]
What a possibility adding a decorator called @CacheResult? Or adding another strategy to CacheUpdate decorator. That would be the cherry on the cake :P

**Comment by joshuaslate** [comment]
I am thinking of adding another strategy to the `@CacheUpdate` decorator. I hope to do it soon, just a bit busy at the moment.

Also, be careful with `Object.assign(todo, todoUpdateInput);` because that will actually mutate your `todo` object at the source 😬 It could cause some hard-to-track bugs. `const todoToUpdate = { ...todo, ...todoUpdateInput };` might be better for your purposes here, but you'll know best 😄

**Comment by luqezman** [comment]
@joshuaslate some people recommend using Object.assign because my Entities sometimes has lifecycle methods, etc.

**Comment by luqezman** [comment]
@joshuaslate Tell me about your strategy regarding of @CacheUpdate.

**Comment by luqezman** [comment]
@joshuaslate news? :P

**Comment by joshuaslate** [comment]
Not yet, busy work week. I hope to look soon.

**Comment by joshuaslate** [comment]
In v7.0.0 this should be solved.

```
@CacheUpdate({ cacheKey: (args, ctx, result) => result.id, cacheKeysToClear: 'todos' })
  async createTodo(task: string): Promise<Todo> {
    const todoAsEntity = await this.todoRepository.create({ task });
    const todo = await this.todoRepository.save(todoAsEntity);

    return todo;
  }
```

**Comment by luqezman** [comment]
Huge Thanks @joshuaslate :-D
