### ISSUE TITLE
Clear all cacheKeys by hashKey

### ISSUE THREAD

**Issue by mklan** [joshuaslate/type-cacheable#221]
Hello. First of thanks for this awesome lib :) I wanted to ask if it is somehow possible to clear all cacheKeys with the same hashKey?

I tried to use CacheClear like this:

```javascript
@CacheClear({
    hashKey: (args) => `projectPermissions-${args[0]}`,
})
async clearProjectCache(projectId: string) {
  console.log('clearing cache for project', projectId);
}
```

but it does not clear and I need to also define a cache key like this:

```javascript
@CacheClear({
    cacheKey: (args) => args[0],
    hashKey: (args) => `projectPermissions-${args[1]}`,
 })
 async clearProjectCache(userId: string, projectId: string) {
   console.log('clearing cache for project-user', projectId);
 }
```

Thank you!

**Comment by joshuaslate** [comment]
Hello! Thank you for the kind words. Currently, it's not possible. I think I could implement this. How would you like the interface for this to work? If no `cacheKey` option is passed in, simply clear all `cacheKey`s with the provided `hashKey` as you have there in your sample code?

**Comment by mklan** [comment]
Hey! Thanks for the fast response! Yes this would be a clean interface in my opinion. Thank you for implementing this feature!

**Comment by joshuaslate** [comment]
Hey! This should be resolved in version 8.0.0, please let me know if there are any issues!

**Comment by mklan** [comment]
Hello joshuaslate thanks for the quick implementation! 
I have an issue with version 8 loading the types. It states:

"Cannot find module '@type-cacheable/core' or its corresponding type declarations."

**Comment by joshuaslate** [comment]
I think this is related to #223. @dmeents I'm going to revert your commit and we can look into this later.

**Comment by joshuaslate** [comment]
Please try v8.0.1 😬
