### ISSUE TITLE
[bug] `@type-cacheable/core` must be as a peerDependency for all adapters

### ISSUE THREAD

**Issue by ruscon** [joshuaslate/type-cacheable#272]
Right now `@type-cacheable/core` indicated in the `dependencies` section, because of this, 2 different versions of the package can be installed in the project and nothing will be cached.

**Comment by joshuaslate** [comment]
Sorry for the delay, I've been busy. If you'd like to open a PR, I can review it sooner, else I'll try to get to this in a couple of weeks.

**Comment by joshuaslate** [comment]
This is resolved in v9.0.1.
