### ISSUE TITLE
[bug] CacheClear is not clearing all the keys if cacheKey is specified as string[]

### ISSUE THREAD

**Issue by pupipipu** [joshuaslate/type-cacheable#274]
when `cacheKey` is set as an array of string for `CacheClear` decorator, it'll only clear out the first key in the array

**Comment by joshuaslate** [comment]
Which adapter are you using?

**Comment by pupipipu** [comment]
we're using [ioredis-adapter](https://github.com/joshuaslate/type-cacheable/tree/master/packages/ioredis-adapter)

**Comment by joshuaslate** [comment]
@pupipipu could I get a bit more context? This test is passing: https://github.com/joshuaslate/type-cacheable/commit/4e694bb19e87f7c7c563d66c623b76a6500c2b8d#diff-ea1aac11c730e1fa8cab288badbc340c9c880f39fbf749beb0dae81429cc479cR350
