### ISSUE TITLE
[question] How to clear keys by pattern

### ISSUE THREAD

**Issue by oschlegel** [joshuaslate/type-cacheable#275]
Hi, i have a question regarding cache keys, maybe you can help me. I have cache keys which look like this: `items_[country]_[language]_[userId]`, where country, language and userId are dynamic values. When a item is created, updated, or deleted i want to clear all cache keys that start with `items_`. Is it possible to clear cache keys by a regex pattern or something similar?

**Comment by oschlegel** [comment]
Can you help me here?

**Comment by joshuaslate** [comment]
Hey there @oschlegel, I believe you can pass something like `{ isPattern: true, cacheKey: 'items_' }`

Please let me know if this works for you. I've got a lot going on in my personal life at the moment and won't be able to offer much more support for the next couple of weeks.

**Comment by oschlegel** [comment]
You are right i totally overread that in the documentation, thanks
