### ISSUE TITLE
Redis adaptor ignores cacheKey and just sets the key to the hashKey

### ISSUE THREAD

**Issue by taybin** [joshuaslate/type-cacheable#3]
When using NodeCache, the generated key in the NodeCache is `hashKey:cacheKey`, as expected.  When using Redis, the generated key is just `hashKey`.  Looking at the RedisAdaptor, it looks like it deliberately parses out the cacheKey and just sets it as a field instead of using it for the key itself.

What's the reasoning behind this behavior?

**Comment by taybin** [comment]
Okay, after digging in more, and seeing that there are unit tests to ensure this behavior, I see that it's working as designed.  But it seems odd to me to use a single redis hash to store the entire cache.  Wouldn't it be simpler to just use a naming scheme like with NodeCache?  It looks like the intent for redis hashes is for each hash to be for a single object instead of as an unbounded namespace.

**Comment by joshuaslate** [comment]
@taybin fair point. This was my misunderstanding (and I guess abuse) of the intent behind redis hashes. I'm very open to a PR if you have time, otherwise I'll try to work on changing this behavior as I have time!
