### ISSUE TITLE
Handle unavailable redis

### ISSUE THREAD

**Issue by jhoobergs** [joshuaslate/type-cacheable#30]
Hi

I got this package up and running, but when the redis server is unavailable, it always returns an error because it can't connect.
I don't want my application to fail because redis is down, i want it to always execute the method when the redis server is down, is it possible to do this easily ?

**Comment by joshuaslate** [comment]
Hi @jhoobergs,

This makes sense. Great feedback, thank you. Today, I don't think there is an easy way. However, I'll work on this and implement a way to make this happen within the next few days.

Thank you!

**Comment by joshuaslate** [comment]
@jhoobergs this should be implemented now in 1.1.0. Please let me know if there are any issues.

**Comment by jhoobergs** [comment]
@joshuaslate I don't see any differences ?

**Comment by joshuaslate** [comment]
Could you please share the error? I wrote some tests locally for if the client's set/get operations are failing and I'm not catching any errors. I'll be happy to debug this with a bit more info :)

**Comment by jhoobergs** [comment]
Sorry for the late response. I'll try to create a detail example this weekend.

**Comment by jhoobergs** [comment]
Example of what is failing: https://github.com/jhoobergs/type-cacheable/commit/d711c56c8899e1cb28bdccafcd3b6b32bace7a95
it works if redis is there, but returns an error if not

I add circle ci testing so you could see the results: https://circleci.com/gh/jhoobergs/type-cacheable/9 (i added you as a collaborator to my fork, so you should be able to see this)

**Comment by joshuaslate** [comment]
Thank you for this, I will dive in early this week and try to figure it out.

**Comment by joshuaslate** [comment]
@jhoobergs, please give this another shot with the latest, 1.2.1, and let me know if this solves your issue. It seemed to for me on your fork.

**Comment by jhoobergs** [comment]
Works like a charm :raised_hands:
