### ISSUE TITLE
Multiple Caches

### ISSUE THREAD

**Issue by paulfrench** [joshuaslate/type-cacheable#303]
Hello, quick question. I can't see how you can setup different named caches. For example, if I have 3 different areas e..g products, orders, sales etc, I would want to create a separate cache per functional area. Each area will have different TTL etc. Is this possible or do I need to use one cache and specify a hashkey for each each functional area?

Cheers

**Comment by paulfrench** [comment]
Okay, I just setup a different cache client for each area

**Comment by joshuaslate** [comment]
Sorry for the delay, I've been busy. You should be able to pass a `cacheClient` in as an argument to each decorator. Is that what you were referring to?
