### ISSUE TITLE
Redis colon in cacheKey

### ISSUE THREAD

**Issue by jhoobergs** [joshuaslate/type-cacheable#39]
Can you explain why having a colon in the cacheKey makes a difference ? (see https://github.com/joshuaslate/type-cacheable/blob/master/lib/adapters/RedisAdapter.ts#L70)

It didn't seem to matter when the value is a Promise of a list, but when it is a Promise of an object, the result is empty if there is a colon in the cacheKey.

**Comment by joshuaslate** [comment]
Hi @jhoobergs,

I thought there was a test covering this case. I'll try to figure out what's going on. The colon is a convention for hashes (which objects are stored as here). More reading: https://stackoverflow.com/questions/3554888/what-is-the-purpose-of-colons-within-redis-keys

I should have time to look into this later this week or over the weekend. Naturally, if you're able to add a failing test case, it'll make things faster for me, but I'll do my best. Thanks for the bug report!

**Comment by joshuaslate** [comment]
In v3.0.0, I believe I got this fixed. Please feel free to re-open the issue if that's not the case. Sorry this took a while, I didn't understand the issue fully.
