### ISSUE TITLE
[BUG] Decorator doesn't function as a lock

### ISSUE THREAD

**Issue by danshapir** [joshuaslate/type-cacheable#444]
**Describe the bug**
When calling the decorated function multiple times before the promise is resolved, it will actually call it multiple times, meaning if I want to cache a request to the DB, if I have 100 calls to that function, 70 of them might trigger a call to the DB before it's actually saved and only the last 30 will be cached.
This basically makes it useless :(

**To Reproduce**
1. Create an async function that takes a second.
2. Call it multiple times
3. See that the inner function is actually triggered...

**Expected behavior**
The function is locked until a response is returned and then it's cached.

**Comment by zhaoyuhang1033** [comment]
same

**Comment by joshuaslate** [comment]
Please try again in v10.0.0.
