### ISSUE TITLE
throw error: ERR command script not support for normal user

### ISSUE THREAD

**Issue by shawnliujw** [joshuaslate/type-cacheable#59]
i tried to use `@Cacheable({ cacheKey: QichachaService.setCacheKey, ttlSeconds: 300 })` to cache my api , but i keep getting the error like below.   

![image](https://user-images.githubusercontent.com/1515146/68528742-c153d900-0331-11ea-908a-5740b9474373.png)

**Comment by joshuaslate** [comment]
Hi @shawnliujw,

Could you please provide me with the following:

- The version of `type-cacheable` you're using
- The version of `redis` you're using
- The implementation of QichachaService.setCacheKey (types included, please, so I can try to recreate)
- The anticipated return type of the method you're trying to cache the results of.

Does this happen every time your decorated method runs, or only on occasion?

Thanks!

**Comment by shawnliujw** [comment]
hi @joshuaslate  , here is the details:

`type-cacheable@2.0.0` . 
`redis@2.8.0` . 
`static setCacheKey(args: any[]) {
    const cachePrefix = 'qcc_company';
    let arg1: any = args[0];
    if (typeof arg1 === 'object') {
      arg1 = JSON.stringify(arg1);
      const md5 = crypto.createHash('md5');
      md5.update(arg1);
      arg1 = md5.digest('hex');
    }
    return `${cachePrefix}_${arg1}`;
  }` . 

the method will return one json object.    

i found very wired things . it keeps generating that error . i use Sentry to collect exception which received 20k error in less than an hour , my app run in the test environment which won't receive too much traffic . so i was wondering somewhere throw error in loop ?

**Comment by shawnliujw** [comment]
@joshuaslate  sorry , seems this error come from another module [@nestjs/terminus](https://github.com/nestjs/terminus) . sorry to raised the wrong issue.

**Comment by joshuaslate** [comment]
@shawnliujw okay, thank you! Good luck :) Thanks for using `type-cacheable`.
