### ISSUE TITLE
[BUG] Doesn't work with node-redis 4.1.0

### ISSUE THREAD

**Issue by taybin** [joshuaslate/type-cacheable#694]
In the node-redis 4.1.0 release, they changed the location of their subpackages.  Quoting from their page:

> ⚠️ In version 4.1.0 we moved our subpackages from @node-redis to @redis. If you're just using npm install redis, you don't need to do anything—it'll upgrade automatically. If you're using the subpackages directly, you'll need to point to the new scope (e.g. @redis/client instead of @node-redis/client).

This doesn't work with the [import statement in the redis-adaptor](https://github.com/joshuaslate/type-cacheable/blob/3e9dbbc3e8b80f638480569c6235856f478698f5/packages/redis-adapter/lib/index.ts#L1)

They really should have incremented the major version for this breaking change, but they didn't.

**Comment by joshuaslate** [comment]
Thanks for the heads up. I just updated. This should work in the latest version. I followed the same semver as them here to hopefully prevent issues for others.

**Comment by taybin** [comment]
Thank you for the quick fix!
