### ISSUE TITLE
[Feature Request] IoRedis Adapter Scan Keys on Redis Cluster 

### ISSUE THREAD

**Issue by klebeer** [joshuaslate/type-cacheable#808]
**Is your feature request related to a problem? Please describe.**
Currently, the IoRedisAdapter **keys** method uses the ioRedis  **scan** command to search for a pattern
The problem is that the scan command only works on no-cluster environments, and when we use the key command, there are not the right responses to the matches.

```typescript
 public async keys(pattern: string): Promise<string[]> {
    let keys: string[] = [];
    let cursor: number | null = 0;

    while (cursor !== null) {
      const result = (await this.redisClient.scan(cursor, 'MATCH', pattern, 'COUNT', 1000)) as
        | [string, string[]]
        | undefined;

      if (result) {
        // array exists at index 1 from SCAN command, cursor is at 0
        keys = [...keys, ...result[1]];
        cursor = Number(result[0]) !== 0 ? Number(result[0]) : null;
      } else {
        cursor = null;
      }
    }

    return keys;
  }
```

**Describe the solution you'd like**
To support search in a  Redis cluster is needed to list all the *master nodes* of the cluster and *scan* in all of those nodes.

```typescript
  public async keys(pattern: string): Promise<string[]> {
    if(this.redisClient instanceof Cluster) {
      const cluster = this.redisClient as Cluster;
      const keys = cluster.nodes('master').map((node) => this.scanKeys(node, pattern));
      return (await Promise.all(keys)).flat();
    }
    return  this.scanKeys(this.redisClient, pattern);
  }
```
**Describe alternatives you've considered**

**Additional context**

**Comment by joshuaslate** [comment]
Thanks for your PR, this is included in the latest release.
