### ISSUE TITLE
Incorrect peer dependency in redis adapter package

### ISSUE THREAD

**Issue by oschlegel** [joshuaslate/type-cacheable#818]
**Describe the bug**
The `@type-cacheable/redis-adapter` package version 14.0.0 has a peer dependency to `@type-cacheable/core` of version 10.0.0 and a dev dependecy to `@type-cacheable/core` of version 11.0.0, this looks not correct to me.

**Expected behavior**
The `@type-cacheable/redis-adapter` package version 14.0.0 should have a peer dependency to `@type-cacheable/core` of version 11.0.0.

**Comment by joshuaslate** [comment]
@oschlegel, thank you for catching this. I was having trouble with Lerna. I'll fix this and release a patch version.
