### ISSUE TITLE
[Question]: how i can disable the whole caching mechanism with a flag

### ISSUE THREAD

**Issue by mspapant** [joshuaslate/type-cacheable#873]
Congratulations for the good work!

**Is your feature request related to a problem? Please describe.**
We want to use just one flag to disable the cache (from the cache manager maybe) for the whole application. This is useful when you want for example to disable the cache from an env setting due to a bug or something. Can you please let me know how can i achieve it?  

**Describe the solution you'd like**
I want to pass an variable to cache manager to stop caching for the whole application

**Describe alternatives you've considered**
I have tried not setting the cache manager but this doesn't work:
```
const cacheIsDisabled = true;
if (cacheIsDisabled) return;

cacheManager.setOptions(<CacheManagerOptions>{
      excludeContext: true
      ttlSeconds: 1000
})
cacheManager.client = nodeCacheAdapter
```

**Additional context**
No

Thanks in advanced!

**Comment by smcelhinney** [comment]
What about?
```
const cacheIsDisabled = true;

cacheManager.setOptions(<CacheManagerOptions>{
      excludeContext: true
      ttlSeconds: cacheDisabled ? 0 : 1000
})
cacheManager.client = nodeCacheAdapter
```

Not exactly what you're looking for I'm sure, but might help your use case?

**Comment by joshuaslate** [comment]
Sorry this took me forever to get to. I have had a lot going on. I've added a `disable()` and `enable()` method on the `cacheManager` to support this usecase in the latest versions.
