### ISSUE TITLE
Conditionally skip caching for values

### ISSUE THREAD

**Issue by oschlegel** [joshuaslate/type-cacheable#880]
**Is your feature request related to a problem? Please describe.**
Sometimes you don't want to cache certain values. For Example: When you integrate a api which is badly coded and returns status 200 but with a error in the body, this would probably be a value you don't want to cache.

**Describe the solution you'd like**
A `isCacheable` option for the `Cachable` decorator which takes a function with the value to be cached as parameter and expects a boolean, wether or not this value should be cached.

**Describe alternatives you've considered**
The application integrating the api has to implement custom logic (for example throwing a error) to prevent the value from being cached.

**Comment by joshuaslate** [comment]
This was included in the latest release. Thank you for your contribution!
