### ISSUE TITLE
[BUG] set is called on cache client even if an error is thrown

### ISSUE THREAD

**Issue by narwajea** [joshuaslate/type-cacheable#904]
**Describe the bug**

I'm using a `IoRedisAdapter` with a custom strategy that inherits from the provided `DefaultStrategy`.

When my decorated function throws an error, Redis `SET` operation is still called.

After investigating a bit, I wonder if maybe [this line](https://github.com/joshuaslate/type-cacheable/blob/main/packages/core/lib/strategies/DefaultStrategy.ts#L73) should be followed by a return statement so that [this line](https://github.com/joshuaslate/type-cacheable/blob/main/packages/core/lib/strategies/DefaultStrategy.ts#L82) is not executed anymore?

Note: [that](https://github.com/joshuaslate/type-cacheable/blob/main/packages/core/lib/strategies/DefaultStrategy.ts#L76-L79) is not included in the version of `type-cacheable` I'm using.

**Expected behavior**

No Redis `SET` operation is executed in case of error thrown by the decorated function.

**Environment:**
 - OS: Windows 11 Pro N
 - Version: `"@type-cacheable/core": "^11.0.0"`
- Adapter: `"@type-cacheable/ioredis-adapter": "^12.0.1"`

**Comment by joshuaslate** [comment]
Hi, thank you for investigating. I'm hoping to look into this soon, just a bit busy at the moment.

**Comment by joshuaslate** [comment]
I released a new major (due to the behavior change, it just seemed safer) that contains the fix you suggested here. Please let me know if this works for you.

**Comment by narwajea** [comment]
Perfect, thank you.
